services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geospatial-metadata-db
    environment:
      POSTGRES_DB: geospatial_metadata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d geospatial_metadata"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: geospatial-metadata-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/geospatial_metadata?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: