/*
  Warnings:

  - You are about to alter the column `fileSize` on the `metadata` table. The data in that column could be lost. The data in that column will be cast from `Int` to `BigInt`.

*/
-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_metadata" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "abstract" TEXT,
    "purpose" TEXT,
    "status" TEXT,
    "updateFrequency" TEXT,
    "parentIdentifier" TEXT,
    "hierarchyLevel" TEXT,
    "hierarchyLevelName" TEXT,
    "characterSet" TEXT,
    "supplementalInfo" TEXT,
    "keywords" TEXT,
    "topicCategory" TEXT,
    "themeKeywords" TEXT,
    "boundingBox" JSONB,
    "spatialResolution" TEXT,
    "coordinateSystem" TEXT,
    "geographicExtent" TEXT,
    "verticalExtent" JSONB,
    "temporalStart" DATETIME,
    "temporalEnd" DATETIME,
    "dateType" TEXT,
    "dateStamp" DATETIME,
    "contactName" TEXT,
    "contactEmail" TEXT,
    "contactOrganization" TEXT,
    "contactRole" TEXT,
    "contactPhone" TEXT,
    "contactAddress" TEXT,
    "metadataContactName" TEXT,
    "metadataContactEmail" TEXT,
    "metadataContactOrganization" TEXT,
    "distributionFormat" TEXT,
    "onlineResource" TEXT,
    "transferOptions" JSONB,
    "scope" TEXT,
    "lineage" TEXT,
    "accuracy" TEXT,
    "completeness" TEXT,
    "consistency" TEXT,
    "positionalAccuracy" TEXT,
    "conformity" JSONB,
    "useConstraints" TEXT,
    "accessConstraints" TEXT,
    "otherConstraints" TEXT,
    "referenceSystem" TEXT,
    "projection" TEXT,
    "featureTypes" TEXT,
    "attributeInfo" JSONB,
    "spatialRepresentationType" TEXT,
    "axisDimensionProperties" TEXT,
    "cellGeometry" TEXT,
    "georectified" BOOLEAN,
    "georeferenceable" BOOLEAN,
    "sniCompliant" BOOLEAN NOT NULL DEFAULT false,
    "sniVersion" TEXT,
    "sniStandard" TEXT,
    "bahasa" TEXT DEFAULT 'id',
    "originalFileName" TEXT,
    "fileSize" BIGINT,
    "featureCount" INTEGER,
    "geometryType" TEXT,
    "dataFormat" TEXT,
    "processingLevel" TEXT,
    "processingHistory" TEXT,
    "xmlContent" TEXT,
    "xmlSchema" TEXT,
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "publishedAt" DATETIME,
    "reviewStatus" TEXT DEFAULT 'draft',
    "approvalDate" DATETIME,
    "ckanId" TEXT,
    "ckanUrl" TEXT,
    "userId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "metadata_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_metadata" ("abstract", "accessConstraints", "accuracy", "approvalDate", "attributeInfo", "bahasa", "boundingBox", "characterSet", "ckanId", "ckanUrl", "completeness", "conformity", "consistency", "contactAddress", "contactEmail", "contactName", "contactOrganization", "contactPhone", "contactRole", "coordinateSystem", "createdAt", "dataFormat", "dateStamp", "dateType", "distributionFormat", "featureCount", "featureTypes", "fileSize", "geographicExtent", "geometryType", "hierarchyLevel", "hierarchyLevelName", "id", "isPublished", "keywords", "lineage", "metadataContactEmail", "metadataContactName", "metadataContactOrganization", "onlineResource", "originalFileName", "otherConstraints", "parentIdentifier", "positionalAccuracy", "processingHistory", "processingLevel", "projection", "publishedAt", "purpose", "referenceSystem", "reviewStatus", "scope", "sniCompliant", "sniStandard", "sniVersion", "spatialResolution", "status", "supplementalInfo", "temporalEnd", "temporalStart", "themeKeywords", "title", "topicCategory", "transferOptions", "updateFrequency", "updatedAt", "useConstraints", "userId", "verticalExtent", "xmlContent", "xmlSchema") SELECT "abstract", "accessConstraints", "accuracy", "approvalDate", "attributeInfo", "bahasa", "boundingBox", "characterSet", "ckanId", "ckanUrl", "completeness", "conformity", "consistency", "contactAddress", "contactEmail", "contactName", "contactOrganization", "contactPhone", "contactRole", "coordinateSystem", "createdAt", "dataFormat", "dateStamp", "dateType", "distributionFormat", "featureCount", "featureTypes", "fileSize", "geographicExtent", "geometryType", "hierarchyLevel", "hierarchyLevelName", "id", "isPublished", "keywords", "lineage", "metadataContactEmail", "metadataContactName", "metadataContactOrganization", "onlineResource", "originalFileName", "otherConstraints", "parentIdentifier", "positionalAccuracy", "processingHistory", "processingLevel", "projection", "publishedAt", "purpose", "referenceSystem", "reviewStatus", "scope", "sniCompliant", "sniStandard", "sniVersion", "spatialResolution", "status", "supplementalInfo", "temporalEnd", "temporalStart", "themeKeywords", "title", "topicCategory", "transferOptions", "updateFrequency", "updatedAt", "useConstraints", "userId", "verticalExtent", "xmlContent", "xmlSchema" FROM "metadata";
DROP TABLE "metadata";
ALTER TABLE "new_metadata" RENAME TO "metadata";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
